name: build-promtail

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  GO_VERSION: "1.22.2"
  SONAR_HOST_URL: "https://sonar.maerskdev.net"
  REGISTRY_IMAGE: harbor.maersk.io/pensieve/guard

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Generate build ID
        id: prep
        run: |
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::liam-${ts}"
      - name: Build image
        id: build
        run: |
          IMAGE_TAG=${{ steps.prep.outputs.BUILD_ID }} make promtail-image
      - name: Import secrets
        uses: hashicorp/vault-action@v2.4.3
        id: secrets
        with:
          url: https://vault.maersk-digital.net
          tlsSkipVerify: false
          exportEnv: false
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            telemetry-kv/data/readable/harbor/mop-write-user PASSWORD;
            telemetry-kv/data/readable/harbor/mop-write-user USERNAME;
      - name: Login to Maersk Harbor
        uses: docker/login-action@v3.0.0
        with:
          registry: harbor.maersk.io
          username: ${{ steps.secrets.outputs.USERNAME }}
          password: ${{ steps.secrets.outputs.PASSWORD }}
      - name: Build Harbor image
        id: build-harbor
        run: |
          docker tag docker.io/grafana/promtail:${{ steps.prep.outputs.BUILD_ID }} harbor.maersk.io/mop/promtail:${{ steps.prep.outputs.BUILD_ID }}
          docker push harbor.maersk.io/mop/promtail:${{ steps.prep.outputs.BUILD_ID }}
